# Generated by Django 5.1.7 on 2025-04-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('inquiry_type', models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling'), ('investment', 'Investment'), ('other', 'Other')], max_length=50)),
                ('heard_about', models.CharField(choices=[('google', 'Google'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('agree_to_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('regional', 'Regional Office'), ('international', 'International Office')], max_length=50)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
