# Generated by Django 5.1.7 on 2025-04-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeardFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InquiryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='heard_about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.heardfrom'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.inquirytype'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='office_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.officetype'),
        ),
    ]
