# Generated by Django 5.1.7 on 2025-04-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_heardfrom_inquirytype_officetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='heard_about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.heardfrom'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.inquirytype'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='office_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.officetype'),
        ),
    ]
