# Generated by Django 5.0.7 on 2025-03-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
