# Generated by Django 5.1.7 on 2025-03-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='build_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
