# Generated by Django 5.0.7 on 2025-03-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_build_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='property',
        ),
        migrations.AddField(
            model_name='feature',
            name='properties',
            field=models.ManyToManyField(related_name='features', to='property.property'),
        ),
    ]
